### ISSUE TITLE
SQL error when creating new concept

### ISSUE THREAD

**Issue by dakira** [oschettler/knowfox#18]
Following the guide in the wiki I created a first concept ("Journal") and was greeted with the following error.

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'attachments.event_id' in 'where clause' (SQL: select * from `attachments` where `attachments`.`event_id` = 1 and `attachments`.`event_id` is not null order by `is_default` desc)
(View: knowfox/resources/views/concept/show.blade.php) 
(View: knowfox/resources/views/concept/show.blade.php)
```

Same error appears when editing existing concepts.

**Comment by dakira** [comment]
This looks like database and code are out of sync. I wasn't able to figure out, yet, where this event_id is actually used, though. So I guess I need some help with this.

**Comment by oschettler** [comment]
Fixed. The list of available types for a concept is merged from three places:

* The entry `types` in file config/knowfox.php
* Packages, e.g. the package `knowfox/entangle` adds its own types
* The entry `types` in the `data` field (which has YAML format) of a user-specific top-level concept titled `Configuration`

Hm, I didn't have a writeup about this Configuration entry. I have added [one](/oschettler/knowfox/wiki/Configuration). Anyways, in my production database I had all the standard types like `concept` or `folder` in the database entry, so they were missing from a fresh database.

I have now added the standard types to the file `config/knowfox.php`, which makes them available on concept creation, so that the default type is _concept_. This fixes your database error.

**Comment by dakira** [comment]
Thanks! I think I'll see if I can work on the bookmarklet a bit. It would be nice if you could directly add tags (or even share) while creating the bookmark.

**Comment by dakira** [comment]
One addition regarding this bug: There seems to be a hard dependency on the latest version of knowfox/entangle. IMO that should be added to composer.json. Currently it is

    "knowfox/entangle": "^1.1",

which says the current code will work with any 1.*.* version. Actually *only* 1.2.2 works. So the line should rather read

    "knowfox/entangle": "^1.2.2",

which allows for any version >=1.2.2 and < 2.0.0.

**Comment by oschettler** [comment]
You are right. I have updated the composer.json

**Comment by oschettler** [comment]
Regarding adding tags: I'd love that, too, but didn't find the time to add it.
